'use strict';
const express = require('express');
const http = require('http');
const { Server } = require('socket.io');
const { MomentumLagEngine } = require('./engine');

const app = express();
const server = http.createServer(app);
const io = new Server(server, { pingInterval: 2000, pingTimeout: 5000 });
const port = process.env.PORT || 8080;
const engine = new MomentumLagEngine({
  onTick: markets => io.emit('tick', { t: Date.now(), markets }),
  onLog: line => { console.log(line); io.emit('log', line); },
});

const dashboard = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>BTC Correlation Combos</title>
<style>
*{box-sizing:border-box;margin:0;padding:0}html{color-scheme:dark}
body{background:#000;color:#fff;font-family:Inter,ui-sans-serif,system-ui,-apple-system,sans-serif;font-weight:700;padding:10px}
.shell{max-width:1500px;margin:auto}.topbar{display:flex;justify-content:space-between;gap:10px;align-items:center;background:#070b10;border:1px solid #172434;border-radius:14px;padding:12px;margin-bottom:9px}
h1{font-size:20px;letter-spacing:.3px}.sub{font-size:10px;color:#7f93a8;margin-top:2px}.brand-icon{font-size:24px}
.pills{display:flex;gap:5px;flex-wrap:wrap;justify-content:right}.pill{border:1px solid #22364b;background:#08111c;border-radius:999px;padding:5px 8px;font-size:9px;color:#9fb1c4;white-space:nowrap}
.live{color:#00ff9d;border-color:#00ff9d55;background:#00ff9d10}.warn{color:#ffc861;border-color:#ffc86155;background:#ffc86110}.bad{color:#ff5566;border-color:#ff556655;background:#ff556610}
.kpis{display:grid;grid-template-columns:repeat(8,minmax(0,1fr));gap:6px;margin-bottom:9px}.kpi,.panel,.market-card,.combo,.result,.feed-item{background:#060a0f;border:1px solid #16232f;border-radius:13px}
.kpi{padding:10px}.label{font-size:8px;text-transform:uppercase;color:#667e94;letter-spacing:.6px}.value{font-size:18px;margin-top:3px}.small{font-size:8px;color:#617589;font-weight:700}
.two-col{display:grid;grid-template-columns:1fr 320px;gap:9px;margin-bottom:9px}.panel{overflow:hidden}.panel-head{display:flex;justify-content:space-between;align-items:center;padding:10px;border-bottom:1px solid #14202c;font-size:11px;color:#8ea2b6}
.chart{height:155px;padding:5px}svg{width:100%;height:100%}.config-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px;padding:9px}.config-item{background:#080f18;border-radius:9px;padding:8px;font-size:8px;color:#657b91}.config-item b{display:block;font-size:11px;color:#fff;margin-top:2px}
.panel+.panel{margin-top:9px}.section{margin-bottom:9px}.markets{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:7px}.market-card{padding:9px}.market-top{display:flex;justify-content:space-between;align-items:flex-start}.asset-name{font-size:15px}.timer{font-size:16px;color:#39d7ff;font-variant-numeric:tabular-nums;text-align:right}.timer small{display:block;font-size:8px;color:#65798d}
.sides{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:8px}.side{background:#05090f;border:1px solid #152430;border-radius:10px;padding:8px}.side-label{font-size:10px;color:#8fa3b7}.up-label{color:#28e0a5}.down-label{color:#ff6b81}.mid{font-size:27px;line-height:1.15;font-variant-numeric:tabular-nums}.quote{font-size:9px;color:#7f93a8}.delta{font-size:9px;margin-top:2px}.green{color:#00ff9d!important}.red{color:#ff4a68!important}.blue{color:#38d6ff!important}.gold{color:#ffd166!important}
.combos,.results,.feeds{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px}.combo,.result,.feed-item{padding:10px}.combo-top{display:flex;justify-content:space-between;gap:6px}.combo-name{font-size:15px}.status{font-size:8px;color:#38d6ff;border:1px solid #38d6ff44;border-radius:99px;padding:3px 6px}.money{font-size:19px}.legs{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:8px}.leg{background:#05090f;border-radius:9px;padding:7px}.leg b{font-size:14px;display:block}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:5px;margin-top:8px}.cell,.metric-cell{background:#05090f;border-radius:8px;padding:6px;font-size:8px;color:#677d92}.cell b,.metric-cell b{display:block;font-size:11px;color:#fff}
.result-name{font-size:14px}.winners{font-size:10px;color:#8da2b7;margin:3px 0}.feed-main{font-size:12px;margin-top:4px}.feed-detail{font-size:8px;color:#687e93;margin-top:2px}.tag-up,.tag-down{border-radius:6px;padding:2px 4px;font-size:9px}.tag-up{color:#28e0a5;background:#28e0a515}.tag-down{color:#ff6b81;background:#ff6b8115}.logs{height:230px;overflow:auto;background:#010407;border-radius:10px;padding:8px;font-family:SFMono-Regular,Consolas,monospace;font-size:9px;font-weight:500;-webkit-overflow-scrolling:touch}.log{white-space:pre-wrap;color:#95a7b9;padding:1px 0}.empty{padding:16px;text-align:center;color:#445467;font-size:11px}
@media(max-width:1150px){.kpis{grid-template-columns:repeat(4,minmax(0,1fr))}.markets{grid-template-columns:repeat(2,minmax(0,1fr))}.combos,.results,.feeds{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(max-width:720px){body{padding:7px}.topbar{flex-direction:column;align-items:stretch}.pills{justify-content:flex-start}.kpis{grid-template-columns:repeat(2,minmax(0,1fr));gap:5px}.two-col{grid-template-columns:1fr}.markets,.combos,.results,.feeds{grid-template-columns:1fr}.mid{font-size:30px}.value,.money{font-size:20px}h1{font-size:17px}}
</style></head><body><div class="shell">
<header class="topbar"><div class="brand"><div class="brand-icon">🔗</div><div><h1>BTC Correlation Combos</h1><div class="sub">BTC UP/DOWN + opposite alt side · combined mid <0.75 · hold to resolution · CLOB WebSocket only</div></div></div><div class="pills"><span class="pill live" id="connection">UI LIVE</span><span class="pill warn" id="clobStatus">CLOB CONNECTING</span><span class="pill warn" id="discoveryStatus">DISCOVERY</span><span class="pill" id="rate">0/s</span><span class="pill" id="uptime">00:00</span></div></header>
<section class="kpis" id="kpis"></section>
<section class="two-col"><div class="panel"><div class="panel-head"><span>Global equity curve</span><strong id="equityValue">—</strong></div><div class="chart"><svg id="equityChart" preserveAspectRatio="none"></svg></div></div><div class="panel"><div class="panel-head"><span>Strategy & connection</span><strong>ACTIVE RULES</strong></div><div class="config-grid" id="configGrid"></div></div></section>
<section class="panel section"><div class="panel-head"><span>Live CLOB order books</span><strong id="tickInfo">WAITING</strong></div><div class="markets" id="marketsGrid"></div></section>
<section class="panel section"><div class="panel-head"><span>Open correlation combos</span><strong id="comboCount">0 OPEN</strong></div><div class="combos" id="combosGrid"></div></section>
<div class="two-col"><div class="panel"><div class="panel-head"><span>Resolved combos · last 2s >0.90</span><strong>SETTLED</strong></div><div class="results" id="resultsGrid" style="padding:8px"></div></div><div class="panel"><div class="panel-head"><span>Execution feed</span><strong>PAPER FOK LEGS</strong></div><div class="feeds" style="padding:8px" id="feedGrid"></div></div></div>
<section class="panel"><div class="panel-head"><span>Server activity</span><strong id="socketStatus">READY</strong></div><div class="logs" id="logsPanel"></div></section>
</div><script src="/socket.io/socket.io.js"></script><script>
let state=null,tickData=null,logs=[],lastRender=0,priceHistory={},lastMessages=0,lastRateAt=Date.now(),rateValue=0;
const $=id=>document.getElementById(id),socket=io({transports:['polling','websocket'],upgrade:true,reconnectionDelay:250,reconnectionDelayMax:1000,timeout:3000});
socket.on('connect',()=>{$('connection').textContent='UI LIVE';$('connection').className='pill live'});socket.on('disconnect',()=>{$('connection').textContent='UI RETRY';$('connection').className='pill warn'});
socket.on('log',line=>{logs.push(line);if(logs.length>300)logs.shift();renderLogs()});socket.on('tick',data=>{tickData=data;if(data.messageCount!=null)updateRate(data.messageCount);requestAnimationFrame(()=>{if(tickData===data){renderLivePrices(data);renderFloating();lastRender=Date.now()}})});
socket.on('state',data=>render(data));
async function refreshState(){try{const r=await fetch('/api/status');render(await r.json())}catch(e){$('connection').textContent='UI RETRY';$('connection').className='pill warn'}}refreshState();setInterval(refreshState,1000);
function num(v){return Number(v||0).toLocaleString(undefined,{maximumFractionDigits:2})}function cash(v){return'$'+Number(v||0).toFixed(2)}function money(v){if(v==null)return'—';const n=Number(v);return(n>0?'+$':n<0?'-$':'$')+Math.abs(n).toFixed(2)}function tone(v){return Number(v)>0?'green':Number(v)<0?'red':''}function price(v){return v==null?'—':Number(v).toFixed(3)}function clock(s){s=Math.max(0,Math.floor(s));return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}function esc(x){return String(x||'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function updateRate(count){const previous=lastMessages;lastMessages=count;if(Date.now()-lastRateAt>=1000){rateValue=Math.max(0,Math.round((count-previous)*1000/(Date.now()-lastRateAt)));lastRateAt=Date.now()}$('rate').textContent=rateValue+'/s'}
function render(d){state=d;$('uptime').textContent=clock(d.uptime);const clob=$('clobStatus');clob.textContent=d.connected?'CLOB LIVE':(d.subscribedTokens?'CLOB RECONNECTING':'CLOB CONNECTING');clob.className='pill '+(d.connected?'live':'warn');const disc=$('discoveryStatus');disc.textContent=d.discovery.currentDiscovered+'/'+d.discovery.expectedMarkets+' NOW';disc.className='pill '+(d.discovery.currentDiscovered===d.discovery.expectedMarkets?'live':'warn');
$('kpis').innerHTML=[['Equity',cash(d.markValue),'',d.bankroll+' bankroll'],['Total P&L',money(d.totalPnl),tone(d.totalPnl),'Since launch'],['Realized P&L',money(d.realizedPnl),tone(d.realizedPnl),'Settled combos'],['Floating P&L',money(d.unrealizedPnl),tone(d.unrealizedPnl),'Live mark'],['Open Cost',cash(d.openValue),'',d.combos.length+' combos'],['Win Rate',(d.winRate==null?'—':d.winRate+'%'),'',(d.wins||0)+'W / '+(d.losses||0)+'L'],['Combo Legs',num(d.positions.length),'','100 SH each'],['Messages',num(d.messageCount),'','CLOB received']].map(k=>'<article class="kpi"><div class="label">'+k[0]+'</div><div class="value '+k[2]+'">'+k[1]+'</div><div class="small">'+k[3]+'</div></article>').join('');
$('equityValue').textContent=cash(d.markValue);renderChart(d.equityCurve||[]);$('configGrid').innerHTML=[['Entry','combined mid < '+d.config.entryMaxSum.toFixed(2)],['Size','100 SH × each leg'],['Exit','hold to resolution'],['Resolution','final 2s > '+d.config.resolutionPrice.toFixed(2)],['Fees',d.config.feeBps+' bps'],['Bankroll',cash(d.bankroll)],['Reconnects',num(d.reconnects)],['Last discovery',d.discovery.lastDiscoveryAt?new Date(d.discovery.lastDiscoveryAt).toLocaleTimeString():'waiting']].map(r=>'<div class="config-item">'+r[0]+'<b>'+r[1]+'</b></div>').join('');buildMarkets(d.markets||[]);renderLivePrices(tickData&&tickData.markets?.length?tickData:{t:Date.now(),markets:d.markets||[]});renderCombos(d.combos||[]);renderResults(d.resolvedCombos||[]);renderFeed(d.trades||[]);renderLogs()}
function buildMarkets(markets){if(!markets.length){$('marketsGrid').innerHTML='<div class="empty">Discovering current-window books…</div>';return}$('marketsGrid').innerHTML=markets.map(m=>'<article class="market-card" id="market-'+m.asset+'"><div class="market-top"><div><div class="asset-name">'+m.asset.toUpperCase()+'</div><div class="small">'+m.slug+'</div></div><div class="timer" id="timer-'+m.asset+'">'+clock(m.remaining)+'<small>T+'+m.elapsed+'s</small></div></div><div class="sides">'+sideHtml(m.asset,'UP')+sideHtml(m.asset,'DOWN')+'</div></article>').join('')}
function sideHtml(asset,outcome){const id=(asset+'-'+outcome).toLowerCase();return'<div class="side"><div class="side-label '+outcome.toLowerCase()+'-label">'+outcome+'</div><div class="mid" id="mid-'+id+'">—</div><div class="quote">B <span id="bid-'+id+'">—</span> · A <span id="ask-'+id+'">—</span></div><div class="quote">SPR <span id="spread-'+id+'">—</span></div><div class="delta" id="delta-'+id+'">HOLD</div></div>'}
function rememberPrice(key,value){if(!Number.isFinite(value))return null;const now=Date.now(),list=priceHistory[key]||(priceHistory[key]=[]);list.push({t:now,p:value});while(list.length&&now-list[0].t>2500)list.shift();const old=list.find(x=>now-x.t<=1800&&x.p!==value)||list[0];return value-old.p}
function renderLivePrices(packet){if(!packet?.markets||!state)return;$('tickInfo').textContent=new Date(packet.t).toLocaleTimeString()+' · '+packet.markets.length+' BOOKS';for(const market of packet.markets){const card=$('market-'+market.asset);if(!card)continue;$('timer-'+market.asset).innerHTML=clock(market.remaining)+'<small>T+'+market.elapsed+'s</small>';for(const side of ['up','down']){const token=market[side],id=market.asset+'-'+side,delta=rememberPrice(id,token.mid);$( 'mid-'+id).textContent=price(token.mid);$('bid-'+id).textContent=price(token.bid);$('ask-'+id).textContent=price(token.ask);$('spread-'+id).textContent=token.spread==null?'—':token.spread.toFixed(3);const el=$('delta-'+id);el.textContent=delta==null?'HOLD':(delta>=0?'▲ +':'▼ ')+delta.toFixed(3);el.className='delta '+(delta>=0?'green':'red')}}}
function renderFloating(){if(!state)return;for(const combo of state.combos||[]){const el=$('floating-'+combo.id);if(el)el.textContent=money(combo.unrealized),el.className='money '+tone(combo.unrealized)}}
function renderCombos(combos){$('comboCount').textContent=combos.length+' OPEN';if(!combos.length){$('combosGrid').innerHTML='<div class="empty">No combo meets combined mid <0.75 yet</div>';return}$('combosGrid').innerHTML=combos.map(c=>'<article class="combo"><div class="combo-top"><div><div class="combo-name">'+esc(c.name)+'</div><div class="small">ENTRY MID '+Number(c.combinedEntryMid).toFixed(3)+' · T+'+Math.floor((Date.now()-c.windowStart)/1000)+'s</div></div><span class="status">HOLDING</span></div><div class="metrics"><div class="metric-cell">COMBO COST<b>'+cash(c.cost)+'</b></div><div class="metric-cell">MARK<b>'+cash(c.markValue)+'</b></div><div class="metric-cell">FLOATING<b class="'+tone(c.unrealized)+'">'+money(c.unrealized)+'</b></div></div><div class="legs">'+c.legs.map(l=>'<div class="leg"><span class="small">'+l.asset.toUpperCase()+' '+l.outcome+'</span><b>'+num(l.shares)+' SH</b><div class="small">ENTRY '+Number(l.entryPrice).toFixed(3)+' · MARK '+Number(l.markPrice??l.entryPrice).toFixed(3)+'</div><div class="small">COST '+cash(l.cost)+' · VALUE '+cash(l.shares*(l.markPrice??l.entryPrice))+'</div></div>').join('')+'</div></article>').join('')}
function renderResults(results){if(!results.length){$('resultsGrid').innerHTML='<div class="empty">No settled combos yet</div>';return}$('resultsGrid').innerHTML=results.map(r=>'<article class="result"><div class="result-name">'+esc(r.name)+' · <span class="'+(r.pnl>=0?'green':'red')+'">'+r.result+'</span><div class="winners">'+esc(r.winner)+'</div></div><div class="money '+tone(r.pnl)+'">'+money(r.pnl)+'<div class="small-money">'+cash(r.payout)+' payout / '+cash(r.cost)+' cost</div></div></article>').join('')}
function renderFeed(trades){if(!trades.length){$('feedGrid').innerHTML='<div class="empty">Waiting for correlation entries…</div>';return}$('feedGrid').innerHTML=trades.slice(0,30).map(t=>'<article class="feed-item"><div class="small">'+new Date(t.timestamp).toLocaleTimeString()+' · '+esc(t.signal.combo)+'</div><div class="feed-main"><span class="'+(t.outcome==='UP'?'tag-up':'tag-down')+'">'+t.asset.toUpperCase()+' '+t.outcome+'</span> '+num(t.shares)+' SH @ '+Number(t.price).toFixed(3)+'</div><div class="feed-detail">Combined mid '+Number(t.signal.combinedMid).toFixed(3)+' · '+cash(t.cost)+' · FOK</div></article>').join('')}
function renderChart(curve){const svg=$('equityChart');if(!curve.length){svg.innerHTML='';return}const values=curve.map(x=>x.equity),low=Math.min(...values),high=Math.max(...values),range=(high-low)||1,w=700,h=160,pad=12,pts=curve.map((point,index)=>[index/Math.max(1,curve.length-1)*w,h-pad-(point.equity-low)/range*(h-pad*2)]),path='M'+pts.map(p=>p[0].toFixed(1)+','+p[1].toFixed(1)).join(' L'),last=pts.at(-1)||[0,h/2],color=state.totalPnl>=0?'#15ff9c':'#ff4a68';svg.innerHTML='<path d="'+path+'" fill="none" stroke="'+color+'" stroke-width="3"/><circle cx="'+last[0]+'" cy="'+last[1]+'" r="5" fill="'+color+'"/>'}
function renderLogs(){const panel=$('logsPanel'),nearBottom=panel.scrollHeight-panel.scrollTop-panel.clientHeight<50;panel.innerHTML=logs.slice(-220).map(line=>{let cls='';if(line.includes('BUY'))cls='log-info';else if(line.includes('WIN'))cls='log-win';else if(line.includes('LOSS')||line.includes('⚠️'))cls='log-loss';return'<div class="log '+cls+'">'+esc(line)+'</div>'}).join('');if(nearBottom)panel.scrollTop=panel.scrollHeight}
setInterval(()=>{if(tickData&&state&&Date.now()-lastRender>100){renderLivePrices(tickData);renderFloating();lastRender=Date.now()}},50);
</script></body></html>`;
app.get('/healthz', (_, response) => response.sendStatus(200));
app.get('/api/status', (_, response) => response.json(engine.buildState()));
app.get('/', (_, request) => request.type('html').send(dashboard));
io.on('connection', socket => socket.emit('state', engine.buildState()));
setInterval(() => io.emit('state', engine.buildState()), 250);
server.listen(port, '0.0.0.0', () => {
  console.log(`BTC correlation combo dashboard listening on :${port}`);
  engine.init().catch(error => console.error(`Init failure: ${error.message}`));
});
